Repository pirogramming/Healthtant, pull requests merged in 2025-08, with the labels that each got.

#15 [Feat] templates, static 폴더 생성/accounts 파일의 로그인 부분 작업중
  accounts/templates/account/login.html
  accounts/templates/account/signup.html
  accounts/templates/accounts/profile.html
  config/settings.py
  static/accounts/accounts_global.css
  static/accounts/accounts_style.css
  static/accounts/accounts_styleguide.css
Labels: feat, style

#16 [Feat] 식사 관리 메인 페이지 기능 구현
  config/settings.py
  config/urls.py
  diets/__init__.py
  diets/admin.py
  diets/apps.py
  diets/migrations/0001_initial.py
  diets/migrations/__init__.py
  diets/models.py
  diets/tests.py
  diets/urls.py
  diets/views.py
  foods/__init__.py
  foods/admin.py
  foods/apps.py
  foods/migrations/0001_initial.py
  foods/migrations/0002_alter_food_food_id.py
  foods/migrations/__init__.py
  foods/models.py
  foods/tests.py
  foods/views.py
  requirements.txt
Labels: feat, comment

#17 [Feat] login.html 초안 작성 및 account 폴더 구조 개선
  accounts/templates/account/signup.html
  config/settings.py
  templates/account/login.html
  templates/account/signup.html
Labels: feat, refactor, style

#19 [Feat] diet_search api 구현
  diets/views.py
Labels: feat, comment

#20 [CI] cicd 구축을 위한 main.yml 파일 생성
  .github/workflows/main.yml
Labels: ci

#24 [Feat] 식사 수정 및 삭제 뷰 구현 완료
  diets/views.py
Labels: feat

#28 [Fix] 실제 DB 값에 맞게 BigIntegerField 모두 FloatField로 수정
  foods/models.py
Labels: feat

#35 [Fix] import 추가
  accounts/views.py
Labels: fix

#50 [Feat] diet_main.html 식사 수정, 삭제 기능 뷰와 연결
  analysis/views.py
  diets/urls.py
  diets/views.py
  static/diets/diets_main.css
  templates/diets/diets_main.html
Labels: feat

#55 [Feat] 메인 nav바 식단관리, 분석하기 url 연결
  templates/main/main_base.html
Labels: feat

#81 [Feat] 하단 nav와 마이페이지 url 연결
  templates/main/main_base.html
Labels: feat

#104 [Fix] Food, Diet 모델 id 필드 UUID로 변경 및 마이그레이션 내역 초기화
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_userprofile_nickname_and_more.py
  accounts/migrations/0002_alter_userprofile_options_userprofile_created_at_and_more.py
  accounts/migrations/0003_merge_20250813_1908.py
  accounts/migrations/0003_userprofile_profile_image.py
  accounts/migrations/0004_alter_userprofile_nickname.py
  accounts/migrations/0005_merge_20250813_2347.py
  accounts/migrations/0005_merge_20250813_2349.py
  accounts/migrations/0005_merge_20250813_2357.py
  accounts/migrations/0006_remove_userprofile_profile_image.py
  accounts/migrations/0006_remove_userprofile_profile_image_url_and_more.py
  accounts/migrations/0007_rename_profile_image_userprofile_profile_image_url.py
  accounts/migrations/0008_merge_20250814_0014.py
  common/nutrition_score.py
  diets/migrations/0001_initial.py
  diets/migrations/0002_alter_diet_options_diet_created_at_diet_updated_at_and_more.py
  diets/models.py
  foods/migrations/0001_initial.py
  foods/migrations/0002_alter_food_food_id.py
  foods/migrations/0003_alter_food_options_food_created_at_food_nrf_index_and_more.py
  foods/migrations/0003_alter_food_vitamina_alter_food_vitaminb_and_more.py
  foods/migrations/0004_alter_food_serving_size_alter_food_weight.py
  foods/migrations/0004_favoritefood.py
  foods/migrations/0005_food_magnesium.py
  foods/migrations/0006_merge_20250813_1908.py
  foods/migrations/0007_alter_food_calorie_alter_food_salt.py
  foods/models.py
Labels: fix

#124 [Feat] 메인페이지, 일반 검색 페이지 js 추가
  config/settings/base.py
  config/settings/local.py
  static/main/js/main.js
  static/search/css/normal_search.css
  static/search/js/normal_search.js
  templates/main/main_mainpage.html
  templates/search/search_page.html
Labels: feat, style

#134 [DB] 불필요한 칼럼 제거 및 모델 정리
  .gitignore
  backup_feat48.patch
  diets/views.py
  foods/migrations/0007_food_nrf_index_food_nutri_score_grade_and_more.py
  foods/models.py
  mypage/views.py
  products/views.py
  scripts/script_clean_data.py
  scripts/script_crawl_naver.py
  scripts/script_insert_food.py
  search/views.py
  static/search/js/normal_search.js
  templates/products/products_detail.html
  templates/search/search_before.html
Labels: refactor, db

#144 [Refact] 상세 검색 정렬 기능 최적화
  analysis/views.py
  search/views.py
Labels: refactor

#148 [Feat] 메인 페이지에 출력되는 식품에 랜덤성 추가 & [Fix] Diet 모델 meal 필드 length 10으로 넉넉하게 늘림
  diets/models.py
  main/views.py
  search/views.py
Labels: feat, fix

#152 [Feat] 상세 검색 페이지 즐겨찾기 오류 해결
  search/views.py
  static/mypage/mypage_favorite_foods.css
Labels: feat, fix

#170 [Fix] 고급 검색 기능 정렬 기능이 빠져있어 order_by 추가
  search/views.py
Labels: fix
